import { describe, expect, it } from 'vitest';
import type { CapturedBenchmarkPlan } from './captured-benchmark-plan';
import { buildCapturedCaptureSlotTemplate } from './captured-capture-slot-template';

const plan: CapturedBenchmarkPlan = {
    datasetId: 'captured-benchmark-draft',
    currentStarterGate: {
        passed: false,
        checks: [],
    },
    promotionActions: [],
    specialistReviewActions: [],
    captureBlueprints: [
        {
            slotId: 'captured-slot-1',
            planTier: 'starter',
            purpose: [
                'fechar gap de quantidade minima de clips capturados',
                'fechar gap de arma distinta',
                'fechar gap de diagnostico esperado',
            ],
            targetReviewStatus: 'reviewed',
            targetTrackingTier: 'clean',
            targetVisibilityTier: 'clean',
            targetOcclusionLevel: 'light',
            targetCompressionLevel: 'light',
            targetDistanceBucket: '0-30m',
            targetPatchVersion: '40.1',
            weaponPolicy: 'new-distinct-weapon',
            opticPolicy: 'any',
            avoidWeaponIds: ['aug'],
            avoidOpticKeys: [],
            requiresExpectedDiagnosis: true,
            requiresSpecialistReview: false,
            notes: 'Escolher uma arma diferente da atual.',
        },
        {
            slotId: 'captured-slot-2',
            planTier: 'starter',
            purpose: ['fechar gap de quantidade minima de clips capturados'],
            targetReviewStatus: 'reviewed',
            targetTrackingTier: 'degraded',
            targetVisibilityTier: 'degraded',
            targetOcclusionLevel: 'moderate',
            targetCompressionLevel: 'medium',
            targetDistanceBucket: '101m+',
            targetPatchVersion: '40.1',
            weaponPolicy: 'any',
            opticPolicy: 'any',
            avoidWeaponIds: [],
            avoidOpticKeys: [],
            requiresExpectedDiagnosis: false,
            requiresSpecialistReview: false,
            notes: 'Cobrir um bucket ainda vazio de distancia/qualidade.',
        },
    ],
    evidenceCaptureBlueprints: [
        {
            slotId: 'sdd-evidence-slot-1',
            planTier: 'sdd-evidence',
            purpose: [
                'fechar gap de clip capturado no patch atual 41.1',
                'fechar gap de optic/optic state distinto no corpus SDD',
            ],
            targetReviewStatus: 'reviewed',
            targetTrackingTier: 'clean',
            targetVisibilityTier: 'clean',
            targetOcclusionLevel: 'light',
            targetCompressionLevel: 'light',
            targetDistanceBucket: '31-60m',
            targetPatchVersion: '41.1',
            weaponPolicy: 'any',
            opticPolicy: 'new-distinct-optic',
            avoidWeaponIds: [],
            avoidOpticKeys: ['red-dot-sight:1x'],
            requiresExpectedDiagnosis: false,
            requiresSpecialistReview: true,
            notes: 'Capturar um optic state diferente no patch atual.',
        },
    ],
    projectedStarterGate: {
        passed: true,
        checks: [],
    },
    currentSddGate: {
        passed: false,
        checks: [],
    },
    projectedSddGate: {
        passed: false,
        checks: [],
    },
};

describe('captured capture slot template', () => {
    it('creates machine-editable slot requests for the missing captured clips', () => {
        const template = buildCapturedCaptureSlotTemplate({
            requestSetId: 'captured-capture-slots-todo-2026-04-14',
            datasetId: plan.datasetId,
            createdAt: '2026-04-14T23:30:00.000Z',
            plan,
        });

        expect(template.datasetId).toBe('captured-benchmark-draft');
        expect(template.slots).toEqual([
            {
                slotId: 'captured-slot-1',
                planTier: 'starter',
                purpose: [
                    'fechar gap de quantidade minima de clips capturados',
                    'fechar gap de arma distinta',
                    'fechar gap de diagnostico esperado',
                ],
                targetReviewStatus: 'reviewed',
                targetTrackingTier: 'clean',
                targetVisibilityTier: 'clean',
                targetOcclusionLevel: 'light',
                targetCompressionLevel: 'light',
                targetDistanceBucket: '0-30m',
                targetPatchVersion: '40.1',
                weaponPolicy: 'new-distinct-weapon',
                opticPolicy: 'any',
                avoidWeaponIds: ['aug'],
                avoidOpticKeys: [],
                requiresExpectedDiagnosis: true,
                requiresSpecialistReview: false,
                notes: 'Escolher uma arma diferente da atual.',
                intakeTemplate: {
                    clipId: 'captured-captured-slot-1',
                    videoPath: null,
                    contactPreviewPath: null,
                    centerPreviewPath: null,
                    sha256: null,
                },
            },
            {
                slotId: 'captured-slot-2',
                planTier: 'starter',
                purpose: ['fechar gap de quantidade minima de clips capturados'],
                targetReviewStatus: 'reviewed',
                targetTrackingTier: 'degraded',
                targetVisibilityTier: 'degraded',
                targetOcclusionLevel: 'moderate',
                targetCompressionLevel: 'medium',
                targetDistanceBucket: '101m+',
                targetPatchVersion: '40.1',
                weaponPolicy: 'any',
                opticPolicy: 'any',
                avoidWeaponIds: [],
                avoidOpticKeys: [],
                requiresExpectedDiagnosis: false,
                requiresSpecialistReview: false,
                notes: 'Cobrir um bucket ainda vazio de distancia/qualidade.',
                intakeTemplate: {
                    clipId: 'captured-captured-slot-2',
                    videoPath: null,
                    contactPreviewPath: null,
                    centerPreviewPath: null,
                    sha256: null,
                },
            },
            {
                slotId: 'sdd-evidence-slot-1',
                planTier: 'sdd-evidence',
                purpose: [
                    'fechar gap de clip capturado no patch atual 41.1',
                    'fechar gap de optic/optic state distinto no corpus SDD',
                ],
                targetReviewStatus: 'reviewed',
                targetTrackingTier: 'clean',
                targetVisibilityTier: 'clean',
                targetOcclusionLevel: 'light',
                targetCompressionLevel: 'light',
                targetDistanceBucket: '31-60m',
                targetPatchVersion: '41.1',
                weaponPolicy: 'any',
                opticPolicy: 'new-distinct-optic',
                avoidWeaponIds: [],
                avoidOpticKeys: ['red-dot-sight:1x'],
                requiresExpectedDiagnosis: false,
                requiresSpecialistReview: true,
                notes: 'Capturar um optic state diferente no patch atual.',
                intakeTemplate: {
                    clipId: 'captured-sdd-evidence-slot-1',
                    videoPath: null,
                    contactPreviewPath: null,
                    centerPreviewPath: null,
                    sha256: null,
                },
            },
        ]);
    });
});
